spring:
  dubbo:
    application:
      name: demo-provider
    base-package: org.lavenderx.dubbo.provider  # dubbo服务发布者所在的包
    registry:
      address: 10.8.10.41                   # zookeeper注册中心的地址
      port: 2181                           # zookeeper注册中心的端口
    protocol:
      name: dubbo
      serialization: hessian2
    provider:
      retries: 0                           # 服务调用重试次数, 服务发布者不给重试, 让服务调用者自己重试