spring:
  dubbo:
    application:
      name: demo-consumer
    base-package: org.lavenderx.dubbo.consumer  # dubbo服务调用者所在的包
    registry:
      address: 10.8.10.41                   # zookeeper注册中心的地址
      port: 2181                           # zookeeper注册中心的端口
    consumer:
      timeout: 3000
      check: true                          # 服务启动时检查被调用服务是否可用
      retries: 3                           # 服务调用重试次数